name: Build

on: [ push, pull_request ]

jobs:
  dist:
    name: Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install SDL & bzip3
      run: |
        sudo apt install -y libsdl2-dev libsdl2-mixer-dev libsdl2-ttf-dev
        wget https://github.com/kspalaiologos/bzip3/releases/download/1.4.0/bzip3-x86_64-linux
        chmod a+x bzip3-x86_64-linux
    - name: Configure
      run: |
        ./autogen.sh
        ./configure
    - name: Make source packages
      run: |
        make dist && gzip -dk sdlgames-1.0.tar.gz && ./bzip3-x86_64-linux sdlgames-1.0.tar && cd ..
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          sdlgames-1.0.tar.gz
          sdlgames-1.0.tar.bz3
